default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: localhost


development:
  <<: *default
  database: my_beans_development

test:
  <<: *default
  database: my_beans_test

production:
  <<: *default
  database: my_beans_production
  username: my_beans_app
  password: <%= ENV['MY_BEANS_DATABASE_PASSWORD'] %>
